// these values are injected at build time
const CONNECTMESSAGER_ENV = process.env.CONNECTMESSAGER_ENV;
const CONNECTMESSAGER_BUILD_VERSION = process.env.CONNECTMESSAGER_BUILD_VERSION;
const CONNECTMESSAGER_BUILD_DATE = process.env.CONNECTMESSAGER_BUILD_DATE;
const CONNECTMESSAGER_MEDIASOUP_BIN_NAME = process.env.CONNECTMESSAGER_MEDIASOUP_BIN_NAME;

const SERVER_VERSION =
  typeof CONNECTMESSAGER_BUILD_VERSION !== 'undefined'
    ? CONNECTMESSAGER_BUILD_VERSION
    : '0.0.0-dev';

const BUILD_DATE =
  typeof CONNECTMESSAGER_BUILD_DATE !== 'undefined' ? CONNECTMESSAGER_BUILD_DATE : 'dev';

const env = typeof CONNECTMESSAGER_ENV !== 'undefined' ? CONNECTMESSAGER_ENV : 'development';
const IS_PRODUCTION = env === 'production';
const IS_DEVELOPMENT = !IS_PRODUCTION;
const IS_TEST = process.env.NODE_ENV === 'test';
const IS_DOCKER = process.env.RUNNING_IN_DOCKER === 'true';

if (IS_PRODUCTION) {
  if (!CONNECTMESSAGER_MEDIASOUP_BIN_NAME) {
    throw new Error('CONNECTMESSAGER_MEDIASOUP_BIN is not defined');
  }
}

export {
  BUILD_DATE,
  IS_DEVELOPMENT,
  IS_DOCKER,
  IS_PRODUCTION,
  IS_TEST,
  SERVER_VERSION,
  CONNECTMESSAGER_MEDIASOUP_BIN_NAME
};


